# App Engine Standard Environment configuration
runtime: nodejs24

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 2
  memory_gb: 2

# Environment variables
env_variables:
  NODE_ENV: production

# Service account
service_account: pure-dialog-sa@gen-lang-client-0874846742.iam.gserviceaccount.com

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network settings
vpc_access_connector:
  name: "projects/gen-lang-client-0874846742/locations/us-west1/connectors/default"
  egress_setting: all-traffic

# Security headers
handlers:
  # Static assets with caching
  - url: /assets
    static_dir: dist/assets
    secure: always
    redirect_http_response_code: 301
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # Favicon and other root static files
  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))
    static_files: dist/\1
    upload: dist/(.*\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))
    secure: always
    redirect_http_response_code: 301
    http_headers:
      Cache-Control: "public, max-age=86400"

  # API routes
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  # Health check
  - url: /health
    script: auto
    secure: always
    redirect_http_response_code: 301

  # All other routes (SPA routing)
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Skip files during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/(?!.*\.(js|json)$).*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.gitignore$
  - ^(.*/)?README\.md$
  - ^(.*/)?\.env\..*$
  - ^(.*/)?cloudbuild\.yaml$
  - ^(.*/)?Dockerfile$
  - ^(.*/)?\.dockerignore$
  - ^(.*/)?deploy\.sh$
  - ^(.*/)?setup\.sh$
  - ^(.*/)?migrate-from-ai-studio\.sh$
  - ^(.*/)?patterns/.*$
  - ^(.*/)?\.cursor/.*$
  - ^(.*/)?AGENTS\.md$
  - ^(.*/)?CLAUDE\.md$
  - ^(.*/)?GEMINI\.md$
  - ^(.*/)?app-structure-diagram\.md$
