substitutions:
  _REGION: us-west1
  _REPOSITORY: puredialog

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - packages/api/Dockerfile
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:$COMMIT_SHA"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:$COMMIT_SHA"

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:$COMMIT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:latest"

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:latest"

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - packages/worker-metadata/Dockerfile
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-metadata:$COMMIT_SHA"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-metadata:$COMMIT_SHA"

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-metadata:$COMMIT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-metadata:latest"

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-metadata:latest"

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - packages/worker-transcription/Dockerfile
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-transcription:$COMMIT_SHA"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-transcription:$COMMIT_SHA"

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-transcription:$COMMIT_SHA"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-transcription:latest"

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-transcription:latest"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-metadata:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/worker-transcription:$COMMIT_SHA"
