# Google Cloud Build configuration for App Engine Standard deployment
steps:
  # Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    id: "install-dependencies"

  # Build the application
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    id: "build-app"

  # Deploy to App Engine
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "app"
      - "deploy"
      - "app.yaml"
      - "--quiet"
      - "--promote"
    id: "deploy-app"

# Substitution variables (kept for compatibility)
substitutions:
  _REGION: "us-west1"
  _SERVICE_NAME: "pure-dialog"
  _SERVICE_ACCOUNT: "pure-dialog-sa@gen-lang-client-0874846742.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
