# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/pure-dialog:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/pure-dialog:latest"
      - "."
    id: "build-image"

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/pure-dialog"
    id: "push-image"

  # Deploy to Cloud Run with secure configuration
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/pure-dialog:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--concurrency"
      - "80"
      - "--timeout"
      - "300"
      - "--service-account"
      - "${_SERVICE_ACCOUNT}"
      - "--set-env-vars"
      - "NODE_ENV=production"
      - "--set-secrets"
      - "GEMINI_API_KEY=gemini-api-key:latest"
    id: "deploy-service"

# Substitution variables
substitutions:
  _REGION: "us-west1"
  _REPOSITORY: "pure-dialog-repo"
  _SERVICE_NAME: "pure-dialog"
  _SERVICE_ACCOUNT: "pure-dialog-sa@gen-lang-client-0874846742.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
