config:
  gcp:project: gen-lang-client-0874846742
  gcp:region: us-west1
  cloudrun:serviceAccount: 211636922435-compute@developer.gserviceaccount.com
  cloudrun:apiServiceName: api
  cloudrun:apiImage: us-west1-docker.pkg.dev/gen-lang-client-0874846742/puredialog-repo/pure-dialog:latest
  cloudrun:metadataServiceName: worker-metadata
  cloudrun:metadataImage: us-west1-docker.pkg.dev/gen-lang-client-0874846742/pure-dialog-repo/pure-dialog:latest
  cloudrun:transcriptionServiceName: worker-transcription
  cloudrun:transcriptionImage: us-west1-docker.pkg.dev/gen-lang-client-0874846742/pure-dialog-repo/pure-dialog:latest
  pubsub:workTopic: work
  pubsub:eventsTopic: events
  pubsub:dlqTopic: work-dlq
  pubsub:metadataSubscription: work-metadata
  pubsub:transcriptionSubscription: work-transcription
  pubsub:eventsMonitorSubscription: events-monitor
  storage:bucketBaseName: ingestion-shared-artifacts
