name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGION: us-west1
  REPOSITORY: puredialog
  PULUMI_STACK: mepuka-org/pure-dialog-infra/dev

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Build and push container images
        run: |
          set -euo pipefail
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=_REGION=${REGION},_REPOSITORY=${REPOSITORY},COMMIT_SHA=${{ github.sha }} \
            --project=${GCP_PROJECT_ID}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install infra dependencies
        working-directory: infra
        run: pnpm install --frozen-lockfile

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5
        with:
          command: version
        env:
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""

      - name: Update stack image tags
        working-directory: infra
        env:
          IMAGE_TAG: ${{ github.sha }}
          PULUMI_CONFIG_PASSPHRASE: ""
        run: |
          set -euo pipefail
          pulumi login --cloud-url https://api.pulumi.com
          pulumi stack select ${PULUMI_STACK} --non-interactive
          pulumi config set cloudrun:apiImage ${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPOSITORY}/api:${IMAGE_TAG} --stack ${PULUMI_STACK} --non-interactive
          pulumi config set cloudrun:metadataImage ${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPOSITORY}/worker-metadata:${IMAGE_TAG} --stack ${PULUMI_STACK} --non-interactive
          pulumi config set cloudrun:transcriptionImage ${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPOSITORY}/worker-transcription:${IMAGE_TAG} --stack ${PULUMI_STACK} --non-interactive

      - name: Deploy infrastructure
        uses: pulumi/actions@v5
        with:
          work-dir: infra
          stack-name: ${{ env.PULUMI_STACK }}
          command: up
          args: --yes
          comment-on-pr: false
        env:
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""
