name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGION: us-west1
  REPOSITORY: puredialog

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push container images
        run: |
          set -euo pipefail

          echo "Building images with commit SHA: ${{ github.sha }}"

          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=_REGION=${REGION},_REPOSITORY=${REPOSITORY},COMMIT_SHA=${{ github.sha }} \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy API to Cloud Run
        run: |
          gcloud run deploy puredialog-api \
            --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPOSITORY}/api:${{ github.sha }} \
            --platform managed \
            --region ${REGION} \
            --allow-unauthenticated \
            --set-env-vars "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" \
            --set-env-vars "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 10 \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Metadata Worker to Cloud Run
        run: |
          gcloud run deploy puredialog-worker-metadata \
            --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPOSITORY}/worker-metadata:${{ github.sha }} \
            --platform managed \
            --region ${REGION} \
            --no-allow-unauthenticated \
            --set-env-vars "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" \
            --set-env-vars "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 5 \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Transcription Worker to Cloud Run
        run: |
          gcloud run deploy puredialog-worker-transcription \
            --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${REPOSITORY}/worker-transcription:${{ github.sha }} \
            --platform managed \
            --region ${REGION} \
            --no-allow-unauthenticated \
            --set-env-vars "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" \
            --set-env-vars "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 3 \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Show deployment results
        if: success()
        run: |
          echo "✅ Deployment successful"
          echo ""
          echo "Service URLs:"
          gcloud run services describe puredialog-api --region ${REGION} --format 'value(status.url)' --project=${{ secrets.GCP_PROJECT_ID }}
          echo ""
          echo "Deployed image tags: ${{ github.sha }}"
